# Generated by Django 6.0.4 on 2026-05-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersubscription'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
