# Generated by Django 6.0.4 on 2026-05-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
