# Generated by Django 6.0.3 on 2026-06-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_contact_email_userprofile_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
