# Generated by Django 6.0.3 on 2026-06-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
